---
title: Anomalie mensili Tmean
output: html_document
params:
  annoF: 2020
  param: tmean
  min: -4
  max: 4
---

Verificare mappa dicembre, zona del Gargano. 

```{r setup,include=FALSE,echo=FALSE,message=FALSE,warning=FALSE}
library("RPostgreSQL")
library("rasterVis")
library("rpostgis")
library("tidyverse")
library("fields")
library("sf")
library("tabularaster")


knitr::opts_chunk$set(include=TRUE,echo=FALSE,message=FALSE,warning=FALSE)

PARAM<-params$param
annoF<-params$annoF

#Disegnare la costa dell'europa?
EUROPA<-TRUE

mesi<-c("Gennaio","Febbraio","Marzo","Aprile","Maggio","Giugno","Luglio","Agosto","Settembre","Ottobre","Novembre","Dicembre")

#minimo e massimo per la legenda
MIN<- params$min
MAX<- params$max

raster::raster("griglia.tif")->griglia

dbConnect(drv="PostgreSQL",dbname="coastline",user="guido",password="guidofioravanti",host="localhost",port=5432)->coastCon
rpostgis::pgGetGeom(conn = coastCon,name = c("italia","costa"))->italiaCoast
spTransform(italiaCoast,CRS("+init=epsg:32632"))->italiaCoast_utm

if(EUROPA){
  rpostgis::pgGetGeom(coastCon,name = c("europa","costa"))->europaCoast
  spTransform(europaCoast,CRS("+init=epsg:32632"))->europaCoast_utm
}  

dbDisconnect(coastCon)

stringr::str_pad(mesi<-seq(1,12,by=1),pad="0",width=2,side="left")->mesi

purrr::map(mesi,.f=function(mm){
  raster(glue::glue("raster_{annoF}_{mm}_{PARAM}.tif"))
})->listaOut

stopifnot(length(listaOut)==12)
brick(listaOut)->mybrick
```

```{r,include=FALSE}
tabularaster::as_tibble(mybrick,xy=TRUE) %>%
  mutate(mm=mesi[dimindex]) %>%
  mutate(mm=factor(mm,levels=mesi,ordered=TRUE))->mydf
```

```{r}
ggplot(data=mydf,aes(x=mm,y=cellvalue))+
  geom_boxplot(aes(fill=mm))+
  ggtitle("Tmean, distribuzione stagione delle anomalie")+
  theme_bw()
```


```{r}
mydf %>%
  mutate(cellvalue=ifelse(cellvalue< MIN,MIN,cellvalue)) %>%
  mutate(cellvalue=ifelse(cellvalue>MAX,MAX,cellvalue))->mydf
```


### Mappa anomalie mensili di tmean

```{r grafici,include=TRUE,fig.height=14,fig.width=12}
ggplot(data=mydf,aes(x=x,y=y,fill=cellvalue))+
  #geom_sf(data=EUROPA,color="#333333",fill="lightgray")+
  geom_tile()+
  ggtitle("Tmean, distribuzione stagione delle anomalie")+
  scale_fill_distiller(type="div",palette="RdBu",na.value="transparent",limits=c(MIN,MAX))+
  facet_wrap(~mm)+
  theme_void()+
  theme(panel.background = element_rect(fill="lightgray"))
```


